//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAWA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipo
    {
        public int idEquipo { get; set; }
        public string detalles { get; set; }
        public string precio { get; set; }
        public string foto { get; set; }
    }
}
